#!/bin/sh

#dwm_bar &
set_wallpaper &
dwmblocks &
#xcompmgr &
picom --experimental-backends &
# dunst &
xset r rate 300 50 &
#sxhkd &
#xmodmap ~/.config/xmodmap/Xmodmap &
unclutter &
exec dwm > ~/.cache/dwm.logs 2>&1

